symbolic_pymc/meta.py
symbolic_pymc/unify.py
tests/test_meta.py

This PR tackles one of the Todo notes in the code by removing from_obj in MetaSymbol and using the multipledispatch library in its place.

Remove from_obj and implement dispatcher

---

.gitignore
requirements.txt
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py

`TFMetaOp.name` comparisons are now more based on the underlying `OpDef`'s type/name (i.e. excluding namespace and underscore + number "uniqueness").
Also, the meta namespace-like helper, `TFlowMetaAccessor`/`mt`, now uses a map that accounts for camel-cased operation names (e.g. `mt.matmul` generates a meta object for the `MatMul` `OpDef`).
Overall, these changes make it much easier to create meta graphs/`etuple`/S-exp forms from scratch (e.g. for unification patterns).  See [the new unification test](https://github.com/pymc-devs/symbolic-pymc/pull/24/files#diff-d849a4f99deb234d3cbbee27f42b69faR80) for a complete example.

Fix some issues involving TF `Operation`/`OpDef` names

---

symbolic_pymc/relations/graph.py
symbolic_pymc/relations/theano/conjugates.py
tests/test_graph.py
tests/theano/test_conjugates.py
tests/theano/test_opt.py

The added `graph_reduceo` can find fixed-points for reduction relations over graphs in both directions.  This means `graph_reduceo` can find fixed-points for a given graph **and** sequences of graphs satisfying given fixed-points, as well as graphs satisfying "patterns"/relations between those two.
Of course the convergence of `graph_reduceo` depends on the relation and terms its given, but it works for strongly normalizing rewrite rules/relations and that's the baseline requirement for completely replacing&mdash;and going well beyond&mdash;Theano's optimization framework.
The general "search" performance can always be addressed with things like `condp`, or any other adjustments to the `cond*` relations that provide run-of-the-mill controlled graph traversal (e.g. depth-limited or weighed …

Introduce a pure miniKanren graph apply/reduce relation

---

conftest.py
symbolic_pymc/meta.py
symbolic_pymc/tensorflow/meta.py
symbolic_pymc/tensorflow/printing.py
symbolic_pymc/theano/meta.py
symbolic_pymc/unify.py
tests/tensorflow/test_printing.py

This PR also introduces a simple TensorFlow graph debug printer in the spirit of `theano.printing.debugprint`.

Some improvements to graph and meta object printing

---

symbolic_pymc/tensorflow/printing.py
tests/tensorflow/test_printing.py

It would throw an exception when shapes were completely unknown.  Now it won't.

Fix TF Shape Printer

---

symbolic_pymc/meta.py
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py

Add meta nodedef

---

symbolic_pymc/tensorflow/printing.py
tests/tensorflow/test_printing.py

These changes will cause `tf_dprint` to only print unique subgraphs once.

Avoid printing duplicate subgraphs

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

`TFlowMetaTensorShape`s were internally using TF `Dimension` objects that were not comparing as expected with `==`.

Fix TFlowMetaTensorShape's use of Dimension objects so that eq is reflexive

---

symbolic_pymc/tensorflow/__init__.py
symbolic_pymc/tensorflow/meta.py
symbolic_pymc/tensorflow/printing.py
tests/tensorflow/__init__.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_printing.py
tests/tensorflow/test_unify.py

Importing `symbolic_pymc` will now no longer disable TensorFlow's eager-mode.  
**Users will still need to provide `symbolic_pymc` TF objects with graphs**, which&mdash;for example&mdash;can be done using the context manager `tensorflow.python.eager.context.graph_mode`.

Remove the need to disable eager-mode globally

---

symbolic_pymc/relations/graph.py
symbolic_pymc/relations/theano/__init__.py
tests/test_graph.py
tests/theano/test_relations.py

This is a fix for #26, and possibly a start toward more efficient relational graph traversal.
```python
from math import log, exp
from operator import add, mul
from unification import var
from kanren import run, eq, conde
from symbolic_pymc.etuple import etuple, ExpressionTuple
from symbolic_pymc.relations.graph import graph_applyo
def etuple_str(self):
if len(self) > 0:
return f"{getattr(self[0], '__name__', self[0])}({', '.join(map(str, self[1:]))})"
else:
return 'noop'
ExpressionTuple.__str__ = etuple_str
del ExpressionTuple._repr_pretty_
def math_reduceo(expanded_term, reduced_term):
"""Construct a goal for some simple math reductions."""
x_lv = var()
return conde(
[eq(expanded_term, etuple(add, x_lv, x_lv)),
eq(reduced_term, etuple(mul, 2, x_lv))],
[eq(expanded_term, etuple(log, …
```

Make graph relations yield results in both directions and all cases

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

The TensorFlow meta accessor, `symbolic_pymc.tensorflow.meta.mt`, will now look for `OpDef`s directly by name and no longer return confusing and marginally useful wrapper functions.
This fixes cases like `mt.RandomStandardNormal`.
Ideally, `mt` would return entirely re-worked backend helper functions: i.e. ones that have all uses of `tf.*` replaced by their corresponding `mt.*` functions.  This would be a pretty involved AST-based endeavour, but it might still be possible to produce a lot more meta object coverage for user-level backend (i.e. `tf`) functionality without solving every edge case.
Closes #51.

Remove meta accessor wrapper functions and add an additional OpDef name lookup

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

Use dtype information when constructing meta output of an operation

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

Everything in a meta graph is (generally) supposed to be immutable (and, thus, hashable), and, since some TF operators take list-based inputs, we need to convert them to tuples.
This shows up when "metatizing" `tf.concat`, and it raises errors when one attempts to debug print these meta graphs.

Turn list arguments into tuples

---

.pylintrc
requirements.txt
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py
tests/tensorflow/utils.py

These updates required changes to the TF tensor and operation name handling, since TF seems to have changed the `OpDef`s behind `__add__` addition.  Likewise, these name changes smooth out some pre-existing inconsistencies between method and function-based operations in TF (e.g. `__mul__` would use the lower-case "mul", which goes against their capitalized naming convention used in most other cases).
Comparisons using `TFlowOpName` are now case insensitive (for better or worse). Also, the `Operation` name is now used as the name value returned by `TFlowMetaTensor.inputs`, along with other related fixes that allow `TFlowMetaTensor.op` to be a logic variable.

Update pinned TF and TFP to latest versions

---

requirements-dev.txt
symbolic_pymc/tensorflow/meta.py
symbolic_pymc/unify.py
tests/tensorflow/test_meta.py
tests/test_unify.py

Expressions like `unify(var('a'), var('b'), {var('a'): np.r_[1, 2]})` fail because `unify` uses the base implementation and `walk`s the `dict` and results in an exception caused by `np.r_[1, 2] == var('b')`.
Also, `TFlowMetaOpDef.__call__` fails when an `OpDef`'s inputs have names that don't match the corresponding `tf.raw_ops.*` function (e.g. `tf.raw_ops.Sum` has arguments named `input` and `axis`, while the `OpDef` for `Sum` uses `input` and `reduction_indices`).

Fix unify when walked values are Numpy arrays

---

requirements-dev.txt
requirements.txt
setup.cfg
symbolic_pymc/etuple.py
symbolic_pymc/meta.py
symbolic_pymc/relations/__init__.py
symbolic_pymc/relations/graph.py
symbolic_pymc/tensorflow/meta.py
symbolic_pymc/tensorflow/unify.py
symbolic_pymc/theano/meta.py
symbolic_pymc/theano/pymc3.py
symbolic_pymc/unify.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py
tests/test_etuple.py
tests/test_meta.py
tests/test_unify.py
tests/theano/test_kanren.py
tests/theano/test_meta.py

Meta objects now use `__slots__` all throughout&mdash;effectively preventing `__dict__` entries from appearing&mdash;and cache their `__hash__` values in a "volatile" `__slots__` entry (named `_hash`) that is cleared based on an object state determined by any non-prefixed `__slots__` entries.  
The `__slots__` values that contribute to the statefulness of cached values are the `__slots__` entries *not prefixed* by an underscore; the ones with underscore prefixes are not part of the "state" and can be/are used to hold cache values.  Underscore prefixed "volatile" `__slots__` entries are cleared when the non-underscored entries are updated (via `__setattr__`).  See `MetaSymbolType.__new__` for details.
These changes appear to have sped up meta object operations quite a bit, but there's …

Make better use of slots and cache hash values

---

README.md
symbolic_pymc/relations/graph.py
symbolic_pymc/relations/theano/__init__.py
tests/test_graph.py
tests/theano/test_relations.py

Now, we have a `graph_applyo` that can be used to perform a single pass over a graph (i.e. with no recursion) and a `reduceo` that performs only a fixed-point recursion of a relation.  The two can be combined to get the same results as before (see the test changes).
Also, `graph_applyo` checks fully reifiable arguments for valid sub-graphs and avoids unnecessarily adding a goal to the stream when there aren't any.

Factor out fixed-point logic from graph relation

---

symbolic_pymc/relations/graph.py
symbolic_pymc/relations/theano/__init__.py
tests/test_graph.py

The relation/goal `lapply_anyo` has been renamed to `seq_apply_anyo`.  It has also been made to return the state with the maximum number of simultaneously successful goals&mdash;for the given relation applied across both sequences&mdash;first.
This change is best explained by a simple example:
```python
from pprint import pprint
from unification import var
from kanren import run, eq, conde
from symbolic_pymc.relations.graph import seq_apply_anyo
def one_to_threeo(x, y):
"""Substitute 1 with 3."""
return conde([eq(x, 1), eq(y, 3)])
q_lv = var('q')
res = run(0, q_lv, seq_apply_anyo(one_to_threeo,
[1, 2, 4, 1, 4, 1, 1],
q_lv))
```
The first result should be the list with *all* substitutions applied:
```python
>>> pprint(res)
([3, 2, 4, 3, 4, 3, 3],
[1, 2, 4, 3, 4, 3, 3],
[3, 2, 4, 1, 4, 3, …
```

Rename and lapply_anyo and make it return max goal conjunctions first

---

symbolic_pymc/etuple.py
tests/tensorflow/test_unify.py

Our custom `UserString` class wasn't working correctly with `etuplize`:
```python
>>> etuplize(TFlowOpName("blah"))
e('b', 'l', 'a', 'h')
```
`etuplize` should not treat `str`s and `UserString`s as regular sequences.  This PR fixes that.

Fix etuplization of strings

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py

The `TFlowOpName` string type was an attempt to "smooth out" some of the name-uniqueness constraints in TF (e.g. so that equality could exist between a meta object with the name `"value:0"` and a recreated base object with an automatically generated name like `"blah/value_1:0"`).  While sometimes convenient, this isn't the right approach, since it causes problems when the ignored name distinctions are actually intended to correspond to distinct base objects.

Remove TFLowOpName

---

Makefile
requirements-dev.txt
setup.cfg
symbolic_pymc/unify.py
symbolic_pymc/utils.py

Add a `make coverage` target that checks coverage differences between the current branch and `master`.  Also, ignore coverage on utility functions that interact with `pdb`.

Add branch diff coverage check and ignore utility functions

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

This PR makes it possible to do simple arithmetic simply.  For example,
```
x_mt = mt.Placeholder('float')
y_mt = mt.Placeholder('float')
x_mt + y_mt
x_mt - y_mt
x_mt * y_mt
x_mt / y_mt
x_mt**y_mt
abs(x_mt)
-x_mt
```

Add overloaded Python arithmetic methods to meta TF tensor

---

.pylintrc
symbolic_pymc/meta.py
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

Two context managers have been introduced:
- `disable_auto_reification`: this prevents meta objects from creating base objects in order to determine undefined values (e.g. shapes, dtypes)
- `enable_lvar_defaults`: this forces `symbolic-pymc` to use logic variables instead of default values (e.g. object names, `NodeDef.attr`).
This PR only adds the aforementioned functionality to the TensorFlow meta objects.

Add ability to disable base object generation and use logic variable defaults

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

These changes allow one to--for instance--create meta objects with logic variable names even when the objects are created through `metatize` (e.g. constant tensors).
Existing meta objects are also preserved--instead of recreated--when they're used as inputs to a meta object that's derived from a "temporary" base object (per `TFlowMetaOpDef.__call__`).
For example, without these changes, the following would succeed:
```python
import tensorflow as tf
from tensorflow.python.eager.context import graph_mode
from symbolic_pymc.tensorflow.meta import mt
with graph_mode():
one_mt = mt(1.0)
test_mt = mt.Add(one_mt, 2.0)
assert test_mt.op.inputs[0] == one_mt
assert test_mt.op.inputs[0] is not one_mt
```
Now, the last assertion will succeed with the `not` removed.

Extend TF meta object creation options to metatize

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

These changes fix a bug that caused cached name values to give the wrong name when using `enable_lvar_defaults('names')`.  They also address a bug with `TFlowMetaTensor.inputs` and logic variable values.

Fix altered metatized objects

---

symbolic_pymc/etuple.py
symbolic_pymc/meta.py
symbolic_pymc/relations/__init__.py
symbolic_pymc/relations/tensorflow/__init__.py
symbolic_pymc/relations/theano/__init__.py
symbolic_pymc/tensorflow/meta.py
symbolic_pymc/tensorflow/unify.py
symbolic_pymc/theano/meta.py
symbolic_pymc/theano/unify.py
symbolic_pymc/unify.py
symbolic_pymc/utils.py
tests/tensorflow/test_kanren.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py
tests/test_meta.py
tests/theano/test_unify.py

- `etuplize` will now only convert valid sequences into etuples
- Meta objects will no longer etuplize into S-expressions like (\<meta type\>, *\<constructor args\>).  This behavior was inconsistent with base-form S-expressions like (\<meta op\>, *\<meta op args\>), which are generally the desired S-expression forms.
- A synthetic TensorFlow operator, `TFlowMetaOperator`, has been introduced and replaces/removes operator-related functionality from the meta `OpDef` class.  The result is an S-expression decomposition with arguments/inputs that (more) exclusively pertain to the operation's high-level meaning.  
For example, `etuplize` now produces S-expressions that are more like `((mt.add, "my_add"), 1, 2)`&mdash;i.e. the old `OpDef` and its "name" parameter are combined into a single …

Refactor etuplization and introduce TensorFlow Operator meta class

---

symbolic_pymc/tensorflow/printing.py
tests/tensorflow/test_printing.py

```python
import numpy as np
from unification import var
from tensorflow.python.eager.context import graph_mode
from symbolic_pymc.tensorflow.meta import mt
from symbolic_pymc.tensorflow.printing import tf_dprint
with graph_mode():
N = 100
X = np.vstack([np.random.randn(N), np.ones(N)]).T.astype('float32')
tt_lv_inputs_mt = mt.Tensor(mt.Operation(var(), var(), var()), 0, var())
tt_const_lv_nodedef_mt = mt.Tensor(mt.Operation(mt.Const.op_def, var(), ()), 0, var())
tt_lv_op_mt = mt.Tensor(var(), 0, var())
test_mt = mt(1.0) + tt_lv_inputs_mt + tt_const_lv_nodedef_mt + tt_lv_op_mt
test_mt += mt(X)
```
```python
>>> tf_dprint(test_mt)
Tensor(AddV2):0,	dtype=float32,	shape=~_17,	"add:0"
|  Tensor(AddV2):0,	dtype=float32,	shape=~_18,	"add:0"
|  |  Tensor(AddV2):0,	dtype=float32,	shape=~_19, …
```

Add dtype and NumPy Const printing to TensorFlow debug print

---

symbolic_pymc/meta.py
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

Now, when we reify TensorFlow meta objects, we check the current graph for any `Operation`s with the same name as the meta `Operation` being reified.  If there is such an `Operation` in the graph, we make sure it's equivalent to the meta `Operation` and return it if it is; otherwise, we throw a new `MetaReificationError`.
Also, this PR introduces a work-around for direct construction of constant tensors (e.g. `mt.const(1, 'int32', 'Const')`).  Previously, this was causing errors because the first argument (i.e. the `value` parameter) wasn't a `TensorProto` type.  We could simply carry around `TensorProto` typed values in the meta `NodeDef`, but that would cause other problems, so&mdash;instead&mdash;a wrapped version of the `tf.raw_ops.Const` function was added; it takes care of the …

Make reify check for existing names in the current TensorFlow graph

---

symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_meta.py

Just some nice refactoring that makes it possible to do `TFlowMetaOperator('add')` instead of having to find the meta `OpDef` manually (e.g. `TFlowMetaOperator(mt.add.op_def)`).

Create TFlowMetaOperators using string names of OpDefs

---

symbolic_pymc/unify.py
tests/tensorflow/test_meta.py
tests/tensorflow/test_unify.py

Meta `OpDef`s, and the dependent `TFlowMetaOperator`s, were unifying when they shouldn't, because the `__all_props__` property was being checked for existence only.  When `__all_props__` was present and empty, `unify` would only compare empty sets and always succeed.

Fix unification for meta objects without properties

---

setup.cfg
symbolic_pymc/constraints.py
symbolic_pymc/relations/__init__.py
symbolic_pymc/relations/graph.py
symbolic_pymc/tensorflow/unify.py
symbolic_pymc/theano/unify.py
symbolic_pymc/unify.py
tests/test_goals.py
tests/test_graph.py
tests/test_kanren.py

Addressing some of the issues in #58.  Should probably move this to the `kanren` project, though.
FYI: We can't really replace the existing `kanren` `lall` and `lany` functions with these new ones until we've implemented a new form of constraints, since a few `symbolic-pymc` goals (indirectly) use `kanren`'s exception-based system (i.e. `EarlyGoalError`s + tuple expressions).

Efficient miniKanren stream functions

---

.pylintrc
symbolic_pymc/tensorflow/graph.py
symbolic_pymc/tensorflow/meta.py
tests/tensorflow/test_graph.py
tests/tensorflow/test_kanren.py
tests/tensorflow/utils.py

Since it's being used more than once in the documentation, I figure it should go in the project itself.  I'll probably do the same for the PyMC4 log-likelihood graph extraction/reconstruction helper functions soon.
Unfortunately, I don't see Grappler normalization/canonicalization being all that useful (e.g. relative to Theano's).

Add a Grappler-based graph normalization function

---

setup.py
symbolic_pymc/theano/ops.py
symbolic_pymc/theano/pymc3.py
symbolic_pymc/theano/random_variables.py

The SciPy `shape` parameter for the gamma types wasn't being used correctly in RV `Op.perform`.

Fix PyMC3 RV Parameterizations

---

symbolic_pymc/theano/pymc3.py
symbolic_pymc/theano/random_variables.py
tests/theano/test_pymc3.py

This PR ties PyMC3's `Distribution.logp` functions to their corresponding `RandomVariable`s via a generic function `logp`.  The `logp` function will also compute log-likelihoods for `Scan`s that output `RandomVariable`s.

Introduce a function that converts RandomVariables to log-likelihoods

---

symbolic_pymc/theano/opt.py
symbolic_pymc/theano/pymc3.py
symbolic_pymc/theano/utils.py
tests/theano/test_opt.py
tests/theano/test_pymc3.py
tests/theano/test_utils.py
tests/theano/utils.py

This PR introduces the steps necessary for computing log-likelihood graphs across a much wider variety of `Scan`-induced random variables/distributions.

Introduce RandomVariable push-out optimization
